
User.create!([
  {email: "mvrosas7@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2016-12-20 20:39:57", last_sign_in_at: "2016-12-15 16:49:00", current_sign_in_ip: "::1", last_sign_in_ip: "::1", username: "mvrosas7", name: "Nella", age: 33, bio: "I change diapers daily. Why yes, I am a mom, but a \"cool mom\" that gets serious whenever necessary.  I am a mom that knows how to be a child with my child; a mom that makes the spare time for studying. I drink an excessive amount of coffee which gives me even more energy to \"fun code\" :) .\r\n\r\nI take life very seriously, but not too serious that I neglect the beauty of it. I like to make whatever I do fun. The key to life for me is embracing pure and simple happiness. Whatever you do, do it with a smile. Whatever you do, do it with being happy to be alive, and don't forget to let your inner child out every single day.\r\n\r\nI have an amazing wife who, of course, sometimes pushes my buttons (we all have them) but she's still amazing. A beautiful and loving family who I am so absolutely proud to be part of. They all still live in Peru (where I was born) but my goal is to eventually bring them to the USA to enjoy the beauty of this amazing and incredible country who has given this 3rd World Country girl the opportunity to become someone. \r\n\r\nOk, I think that's enough. Whoever is reading this: Have a great day! ", school: "Universidad San Ignacio de Loyola, Lima Peru. Tech Talent South, Charlotte NC.", work: "Everywhere"},
  {email: "student0@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, username: "awesomeStudent0", name: nil, age: nil, bio: nil, school: nil, work: nil},
  {email: "student1@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, username: "awesomeStudent1", name: nil, age: nil, bio: nil, school: nil, work: nil},
  {email: "student2@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, username: "awesomeStudent2", name: nil, age: nil, bio: nil, school: nil, work: nil},
  {email: "student3@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, username: "awesomeStudent3", name: nil, age: nil, bio: nil, school: nil, work: nil},
  {email: "student4@gmail.com", password: "password", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, username: "awesomeStudent4", name: nil, age: nil, bio: nil, school: nil, work: nil}
])
Friendship.create!([
  {user_id: 2, friend_id: 5, state: "active", friended_at: "2016-12-20 01:30:32"},
  {user_id: 1, friend_id: 6, state: "active", friended_at: "2016-12-20 01:42:00"},
  {user_id: 1, friend_id: 3, state: "pending", friended_at: nil}
])
